import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Syne } from "next/font/google";
import "./globals.css";
import Background from "@/background";
import Navbar from "@/Navbar";
import HeroSection from "@/HeroSection";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import AboutMe from "@/AboutMe";

// Replace Geist with Inter since Geist is having issues
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const syne = Syne({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-syne',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${syne.variable} relative min-h-screen`}>
        <Background />
        <Navbar />
        <HeroSection />
        <AboutMe />

        <main className="relative z-10 pt-16">
          {children}
        </main>
      </body>
    </html>
  );
}
